[prune]
  non-go = true
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.5.7"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  revision = "b0d76e0fc7e8bc9abf66250596ca36a6aff9087c"
  source = "github.com/cezarsa/fasthttp"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "github.com/google/gops"
  branch = "master"
